sources:
  - name: inventory
    handler:
      graphql:
        endpoint: http://localhost:4001/graphql
  - name: bookings
    handler:
      graphql:
        endpoint: http://localhost:4002/graphql
  - name: ops
    handler:
      graphql:
        endpoint: http://localhost:4003/graphql
  - name: billing
    handler:
      graphql:
        endpoint: http://localhost:4004/graphql
  - name: identity
    handler:
      graphql:
        endpoint: http://localhost:4005/graphql
  - name: listings
    handler:
      graphql:
        endpoint: http://localhost:4006/graphql
  - name: legal
    handler:
      graphql:
        endpoint: http://localhost:4007/graphql
  - name: ai
    handler:
      graphql:
        endpoint: http://localhost:4008/graphql
serve:
  port: 4000
